project:
  type: website

website:
  title: "ISSS608-Coursework"
  navbar:
    left: 
      - text: "Hands-On Exercise"
        menu: 
          - text: "Hands-On Exercise 1"
            href: "HE01.html"
      - text: "In-Class Exercise"
        menu: 
          - text: "In-Class Exercise 1"
            href: "IE01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - solar
      - brand
    css: styles.css
    toc: true

editor: visual

