project:
  type: website

website:
  title: "ISSS608-Coursework"
  navbar:
    left: 
      - text: "Hands-On Exercise"
        menu: 
          - text: "Hands-On Exercise 1"
            href: "Hands-On_Exercise/Hands-On_Exercise01/HE01.html"
          - text: "Hands-On Exercise 2"
            href: "Hands-On_Exercise/Hands-On_Exercise02/HE02.html"
          - text: "Hands-On Exercise 3-1"
            href: "Hands-On_Exercise/Hands-On_Exercise03/HE03-1.html"
      
      - text: "In-Class Exercise"
        menu: 
          - text: "In-Class Exercise 1"
            href: "In-Class_Exercise/In-Class_Exercise01/IE01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      
brand:
  color:
    palette:
      morandi-gray: "#b5b5b5"
      morandi-blue: "#92a8d1"
      morandi-dusty: "#a29bfe"
      background-off-white: "#faf9f6" 
      text-charcoal: "#4a4e69"      
    
    background: "#faf9f6"
    foreground: "#4a4e69"
    primary: "#8e9aaf"    
    secondary: "#b2967d"       
  
  typography:
    fonts:
      - family: "Inter"        
        source: google
      - family: "Cardo" 
        source: google
    base: "Inter"
    headings: "Cardo"

format:
  html:
    theme:
      - plain
      - brand
    css: styles.css
    toc: true
    code-block-bg: "#f0f0ed"
    code-block-border-left: "#8e9aaf"

editor: visual

